# Generated by Django 5.2.7 on 2025-10-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avatar_user_bio_user_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('broker', 'Broker'), ('buyer', 'Buyer'), ('agent', 'Real Estate Agent')], default='buyer', max_length=10),
        ),
    ]
