# Generated by Django 5.2.7 on 2025-10-27 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateAgentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company/Agency name where you work', max_length=100)),
                ('license_number', models.CharField(help_text='Your real estate license number', max_length=50)),
                ('license_expiry', models.DateField(help_text='License expiry date')),
                ('years_experience', models.PositiveIntegerField(help_text='Years of real estate experience')),
                ('bio', models.TextField(help_text='Brief biography and professional background')),
                ('specializations', models.CharField(blank=True, help_text='Areas of specialization (optional)', max_length=255)),
                ('contact_phone', models.CharField(help_text='Professional contact phone', max_length=20)),
                ('contact_email', models.EmailField(help_text='Professional email address', max_length=254)),
                ('license_document', models.FileField(help_text='Upload your license document (PDF/Image)', upload_to='licenses/')),
                ('id_document', models.FileField(help_text='Upload government ID (PDF/Image)', upload_to='id_docs/')),
                ('business_registration', models.FileField(blank=True, help_text='Business registration document (if applicable)', null=True, upload_to='business_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs More Information')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_feedback', models.TextField(blank=True, help_text='Admin feedback and comments')),
                ('requested_documents', models.TextField(blank=True, help_text='Additional documents requested from applicant')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_application', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
