# Generated by Django 5.2.7 on 2025-11-17 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_agent_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Admin Login'), ('logout', 'Admin Logout'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('approve', 'Approve Item'), ('reject', 'Reject Item'), ('ban', 'Ban User'), ('unban', 'Unban User'), ('verify', 'Verify Item'), ('refund', 'Process Refund'), ('export', 'Export Data'), ('settings', 'Change Settings'), ('permission', 'Change Permissions')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('target_model', models.CharField(blank=True, help_text='Model affected', max_length=100, null=True)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='ID of affected record', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of admin')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device info', null=True)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Device details')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_high_risk', models.BooleanField(default=False, help_text='High-risk action')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('activity', 'Admin Activity'), ('system', 'System Alert'), ('security', 'Security Alert'), ('payment', 'Payment Alert'), ('user', 'User Alert')], default='activity', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.adminactivitylog')),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['admin', '-timestamp'], name='accounts_ad_admin_i_4e485b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['action_type', '-timestamp'], name='accounts_ad_action__7e566c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['is_high_risk', '-timestamp'], name='accounts_ad_is_high_4b4850_idx'),
        ),
    ]
