# Generated by Django 5.2.7 on 2025-11-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminactivitylog_adminnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object containing admin permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin_active',
            field=models.BooleanField(default=False, help_text='Whether this admin account is active'),
        ),
    ]
