# Generated by Django 5.2.7 on 2025-11-17 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_admin_permissions_user_is_admin_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('activity', 'Admin Activity'), ('system', 'System Alert'), ('security', 'Security Alert'), ('payment', 'Payment Alert'), ('user', 'User Alert'), ('permission_request', 'Permission Request')], default='activity', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminPermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('manage_users', 'User Management'), ('manage_properties', 'Property Management'), ('manage_payments', 'Payment Management'), ('manage_premium', 'Premium Features Management'), ('manage_content', 'Content Management'), ('view_logs', 'View System Logs'), ('export_data', 'Export Data'), ('delete_data', 'Delete Data'), ('system_settings', 'System Settings')], max_length=20)),
                ('reason', models.TextField(help_text='Why do you need this permission?')),
                ('justification', models.TextField(help_text='How will you use this permission responsibly?')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Super Admin review notes')),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('requesting_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permission_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Permission Request',
                'verbose_name_plural': 'Admin Permission Requests',
                'ordering': ['-requested_at'],
                'unique_together': {('requesting_admin', 'permission_type', 'status')},
            },
        ),
    ]
