# Generated by Django 5.2.7 on 2025-10-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_image_options_image_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='Enter custom amenities (one per line or comma-separated)', null=True),
        ),
    ]
